name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Existing steps remain the same...
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Pull docker images
        run: docker compose pull

      - name: pre-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make run-pre-commit && make clean-pre-commit

      - name: up
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make up

      - name: Set correct permissions for tests
        run: |
          sudo chmod -R 777 ${{ github.workspace }}

      - name: Create reports output folder
        run: |
          mkdir -p ${{ github.workspace }}/reports
          chmod -R 777 ${{ github.workspace }}/reports

      # Modified test step to include coverage
      - name: tests with coverage
        run: |
          docker compose run --rm -v ${{ github.workspace }}/reports:/reports dev pytest . \
            --tb=auto \
            --junitxml=/reports/test-results.xml \
            --cov=. \
            --cov-report=xml:/reports/coverage.xml \
            --cov-report=html:/reports/coverage-html \
            --cov-fail-under=80

      # Upload coverage reports
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            ${{ github.workspace }}/reports/coverage.xml
            ${{ github.workspace }}/reports/coverage-html
        if: ${{ always() }}

      # Existing test results upload and display steps...
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: ${{ github.workspace }}/reports/**/*.xml
        if: ${{ always() }}

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: ${{ github.workspace }}/reports/*.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results

      # Cleanup steps remain the same...
      - name: Cleanup
        if: always()
        run: |
          docker compose down -v --remove-orphans

      - name: 'Cleanup build folder'
        if: always()
        run: |
          ls -la ./
          sudo rm -rf ${{ github.workspace }}/*
          ls -la ./